export const ROUTES = {
  LOGIN: "/login",
  USER: "/user",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  CREATE_USER: "/create",
  CREATE_PRODUCT: "/productos/crear",
  CREATE_CATEGORY: "/categorias/crear",
  CREATE_COMANDA: "/comandas/crear",
  CATEGORY: "/categorias",
  CATEGORY_DETAIL: "/categorias/:id",
  PRODUCT: "/productos",
  PRODUCT_DETAIL: "/productos/:id",
  COMANDA: "/comandas",
  COMANDA_DETAIL: "/comandas/:id",
  COMANDA_CREAR: "/comandas/crear?id=:id",
  COMANDA_PAGAR: "/comandas/:id/pagar",
  GET_IVA: "/configuracion/iva",
  SET_IVA: "/configuracion/iva",
  GET_MONEDA: "/configuracion/moneda",
  SET_MONEDA: "/configuracion/moneda",
  MESAS: "/mesas",
  TOTAL_MESAS: "/configuracion/total-mesas",
};
